---
# Configuration version, don't edit this.
config-version: 2.0.1

language: en-US

currency:
  name: USD
  symbol: $

  balance:
    default-balance: 0
    balance-cap: 1000 # Has no effect if enable-balance-cap is left false
    enable-balance-cap: false

  payment:
    minimum-payment: 10
    maximum-payment: 100

database:
  provider: sqlite
  threads: 2 # Number of threads to use for the database query processing, 2 is recommended

  mysql:
    host: 127.0.0.1
    username: your_username
    password: password
    schema: db_name
    port: 3306

  sqlite:
    file: players.db
...
